// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGFzM3z9S9kODUcwkWikdP9SZ8nz440Zs',
    appId: '1:46846239591:web:aecc89f5c9c80a70d785c2',
    messagingSenderId: '46846239591',
    projectId: 'pulsoscardiacos-57c47',
    authDomain: 'pulsoscardiacos-57c47.firebaseapp.com',
    storageBucket: 'pulsoscardiacos-57c47.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_OtEy--SVwdjCToSvSx9fpAs5PNEesXo',
    appId: '1:46846239591:android:16a3d07d2b6655e7d785c2',
    messagingSenderId: '46846239591',
    projectId: 'pulsoscardiacos-57c47',
    storageBucket: 'pulsoscardiacos-57c47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-rd9tP3M00N6RR_Tjmt4tJyHHF_KI6GE',
    appId: '1:46846239591:ios:27b84c1a3e37e609d785c2',
    messagingSenderId: '46846239591',
    projectId: 'pulsoscardiacos-57c47',
    storageBucket: 'pulsoscardiacos-57c47.appspot.com',
    iosClientId: '46846239591-ehg8gcrgurslne7fkvnqhsjitf0barn5.apps.googleusercontent.com',
    iosBundleId: 'com.example.bluetooh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-rd9tP3M00N6RR_Tjmt4tJyHHF_KI6GE',
    appId: '1:46846239591:ios:27b84c1a3e37e609d785c2',
    messagingSenderId: '46846239591',
    projectId: 'pulsoscardiacos-57c47',
    storageBucket: 'pulsoscardiacos-57c47.appspot.com',
    iosClientId: '46846239591-ehg8gcrgurslne7fkvnqhsjitf0barn5.apps.googleusercontent.com',
    iosBundleId: 'com.example.bluetooh',
  );
}
